---
title: "Untitled"
output: html_document
date: "2023-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}
# Define UI ---------
ui <- fluidPage(
  titlePanel("My Shiny App"),
  
  sidebarLayout(position = "right",
    sidebarPanel(
      h3("Installation", align="left"),
      p("Shiny is availabel on CRAN, so you can install it in the usual way from your R console:"),
      code("install.packages(\"shiny\")"), br(), br(), br(), br(), br(), br(),
      img(src = "rstudio.png", height = 70, width = 200),
      p("Shiny is product of", span("RStudio", style="color:blue"))),
    mainPanel(
            h2("Introducing Shiny"),
            p("Shiny is  a new package from RStudio that makes it ", em("incredibly easy"), "to build interactive web applications with R."), 
            br(), br(), p("For an introduction and live examples, visit the", span("Shiny homepage", style="color:blue")),
            br(), br(), br(),
            h3("Features"),
            p("- Build userful web aplications with only a few lines of code—no Javascript required."),
            p("- Shiny application are automatically 'live' in the same way that", strong("spreadsheet"), "are live. Outputs change instantly as users modify inputs, without requiring a reload of the browser") 
    )
  )
)


# Define Server Logic ---------
server <-  function(input, output) {

}


# Run the app ----
shinyApp(ui = ui, server = server)
```